(()=>{
if(globalThis.__TOTP_VAULT_INLINE_PICKER__)return;globalThis.__TOTP_VAULT_INLINE_PICKER__=true;
const OTP=/(totp|\botp\b|2fa|mfa|one[\s_-]?time|verification|verify|authenticator|security[\s_-]?code|login[\s_-]?code|passcode|c[oó]digo|verificaci[oó]n|autenticaci[oó]n|clave[\s_-]?temporal)/i;
const NO=/(^|[\s_-])(qty|quantity|cantidad|units?|unidades?|product[\s_-]?(qty|quantity)|cart[\s_-]?(qty|quantity))([\s_-]|$)/i;
const ICONS=new Set(['outlook','microsoft','google','github','aws','azure','cloudflare','apple','meta','dropbox','vpn','generic']);
const COLORS={"1c485f":"#1C485F","08709c":"#08709C","95cbc0":"#95CBC0","d4c299":"#D4C299","777778":"#777778","42b8af":"#42B8AF","cfdf9e":"#CFDF9E","ecd799":"#ECD799","fbb38a":"#FBB38A","e77292":"#E77292"};
let target=null,host=null,root=null,panel=null,list=null,search=null,entries=[],timer=null,watch=null,opened=0;
const visible=e=>{if(!(e instanceof HTMLInputElement)||e.disabled||e.readOnly)return false;let r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!='none'&&s.visibility!='hidden'&&+s.opacity>0};
const attrs=e=>[e.id,e.name,e.placeholder,e.autocomplete,e.getAttribute('aria-label'),e.getAttribute('inputmode'),e.getAttribute('pattern'),e.title].filter(Boolean).join(' ').toLowerCase();
const context=e=>{let a=[attrs(e)];try{if(e.labels?.length)a.push(...[...e.labels].map(x=>x.innerText||''))}catch{}let p=e.parentElement;for(let i=0;p&&i<2;i++,p=p.parentElement){let t=(p.innerText||'').trim();if(t.length<500)a.push(t)}return a.join(' ').toLowerCase()};
function score(e){if(!visible(e))return-999;let type=(e.type||'text').toLowerCase(),a=attrs(e),c=context(e);if(type==='text'||['hidden','checkbox','radio','file','submit','button','reset','range','color'].includes(type)||NO.test(a))return-999;if(type==='number'&&!OTP.test(a)){let mn=parseFloat(e.min),v=parseFloat(e.value);if(Number.isFinite(mn)&&mn>=1&&Number.isFinite(v)&&v>=0&&v<=99)return-999}let n=/numeric|decimal|tel|number/.test(`${e.inputMode} ${type}`),m=parseInt(e.maxLength,10),s=0;if((e.autocomplete||'').toLowerCase()==='one-time-code')s+=220;if(/\b(totp|otp|2fa|mfa)\b/i.test(a))s+=130;if(OTP.test(a))s+=100;if(OTP.test(c))s+=65;if(n)s+=15;if(m===6||m===8)s+=38;if(m===1&&n)s+=28;if(type==='password'&&OTP.test(c))s+=15;return s}
function group(e){if(parseInt(e.maxLength,10)!==1)return null;let scope=e.form||e.parentElement||document,x=[...scope.querySelectorAll('input')].filter(i=>visible(i)&&parseInt(i.maxLength,10)===1);if(x.length<6)return null;let k=x.indexOf(e);for(let n of[6,8]){let st=Math.max(0,Math.min(k,x.length-n)),g=x.slice(st,st+n);if(g.includes(e))return g}return null}
function candidate(e){let s=score(e),g=group(e);if(g&&(s>=35||g.some(x=>OTP.test(context(x)))))return{inputs:g,anchor:g[g.length-1],score:Math.max(70,s)};return s>=52?{inputs:[e],anchor:e,score:s}:null}
function best(){let b=null;for(let e of document.querySelectorAll('input')){let x=candidate(e);if(x&&(!b||x.score>b.score))b=x}return b}
function same(a,b){return a&&b&&a.inputs.length===b.inputs.length&&a.inputs.every((x,i)=>x===b.inputs[i])}
function setTarget(t){if(!t||!t.anchor?.isConnected){remove();return}if(same(target,t)&&host?.isConnected){position();return}target=t;mount();position()}
const css=`:host{all:initial;--a:#1C485F}.b,.p{pointer-events:auto}.b{width:30px;height:30px;border:1px solid #9fb2bb;border-radius:9px;background:#e7ecef;display:grid;place-items:center;cursor:pointer;opacity:.72}.b:hover,.b.on{background:var(--a);opacity:1}.b svg{width:18px;fill:none;stroke:#18313c;stroke-width:1.8}.b:hover svg,.b.on svg{stroke:white}.p{position:absolute;right:0;top:36px;width:min(326px,calc(100vw - 20px));max-height:min(420px,calc(100vh - 70px));overflow:hidden;border:1px solid #496978;border-radius:16px;background:#0c1e27;color:#eff7fa;font:13px system-ui;display:flex;flex-direction:column}.p[hidden]{display:none}.h{padding:11px;border-bottom:1px solid #294755}.t{display:flex;justify-content:space-between;font-weight:700;margin-bottom:8px}.x{border:0;background:none;color:#b8d9ea;font-size:18px;cursor:pointer}.q{width:100%;box-sizing:border-box;border:1px solid #496978;border-radius:9px;background:#153647;color:#eff7fa;padding:8px}.l{overflow:auto;padding:6px}.r{width:100%;border:0;border-radius:10px;background:none;color:inherit;display:grid;grid-template-columns:34px 1fr auto;gap:8px;align-items:center;padding:8px;cursor:pointer;text-align:left}.r:hover{background:#153647}.i{width:34px;height:34px;border-radius:9px;display:grid;place-items:center;overflow:hidden;background:#153647;font-size:10px;font-weight:800}.i img{width:100%;height:100%;object-fit:contain}.n{font-weight:700}.m{font-size:10px;color:#b8d9ea}.c{text-align:right;font:700 14px monospace}.s{display:block;font:9px system-ui;color:#b8d9ea;margin-top:3px}.e,.lock{padding:15px;text-align:center;color:#b8d9ea}.lock strong{display:block;color:#eff7fa}.open{margin-top:9px;border:1px solid #496978;border-radius:9px;background:#153647;color:#eff7fa;padding:8px;cursor:pointer}`;
function mount(){remove(false);host=document.createElement('div');host.setAttribute('data-totp-vault-inline','');Object.assign(host.style,{position:'fixed',width:'30px',height:'30px',zIndex:'2147483647',pointerEvents:'none'});root=host.attachShadow({mode:'closed'});root.innerHTML=`<style>${css}</style><button class=b type=button title="Elegir TOTP"><svg viewBox="0 0 24 24"><path d="M12 2 20 5v6c0 5.2-3.1 9.1-8 11-4.9-1.9-8-5.8-8-11V5Z"/><path d="M9 11V9a3 3 0 0 1 6 0v2"/><rect x=8 y=11 width=8 height=6 rx=2/></svg></button><div class=p hidden><div class=h><div class=t><span>TOTP Vault</span><button class=x type=button>×</button></div><input class=q type=search placeholder="Buscar cuenta…"></div><div class=l></div></div>`;panel=root.querySelector('.p');list=root.querySelector('.l');search=root.querySelector('.q');let b=root.querySelector('.b');b.style.pointerEvents=panel.style.pointerEvents='auto';b.onclick=async e=>{if(!e.isTrusted)return;if(panel.hidden)await open();else close()};root.querySelector('.x').onclick=e=>{if(e.isTrusted)close()};search.oninput=()=>render(search.value);(document.documentElement||document.body).append(host)}
function position(){if(!host||!target?.anchor?.isConnected)return;let r=target.anchor.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight){host.style.display='none';return}host.style.display='block';let left=r.right+6+30<=innerWidth-6?r.right+6:Math.max(6,r.right-36),top=Math.max(6,Math.min(innerHeight-36,r.top+(r.height-30)/2));host.style.left=`${Math.round(left)}px`;host.style.top=`${Math.round(top)}px`}
function theme(k){host?.style.setProperty('--a',COLORS[k]||COLORS['1c485f'])}
async function open(){panel.hidden=false;root.querySelector('.b').classList.add('on');list.innerHTML='<div class=e>Cargando…</div>';search.value='';opened=Date.now();position();try{let r=await chrome.runtime.sendMessage({type:'totpVault:inline:list'});if(!r?.ok)throw Error(r?.error||'No se pudo leer la bóveda.');theme(r.colorTheme);if(r.locked){locked();return}entries=r.entries||[];render('');countdown();setTimeout(()=>search?.focus(),0)}catch(e){list.innerHTML=`<div class=e>${esc(e.message)}</div>`}}
function locked(){stop();list.innerHTML='<div class=lock><strong>Bóveda bloqueada</strong>Desbloquea TOTP Vault para elegir una cuenta.<br><button class=open type=button>Abrir TOTP Vault</button><div class=m style="margin-top:7px">Se actualizará automáticamente al desbloquear.</div></div>';root.querySelector('.open').onclick=async e=>{if(e.isTrusted)await chrome.runtime.sendMessage({type:'totpVault:inline:openPopup'})};let start=Date.now();clearTimeout(watch);let check=async()=>{if(panel?.hidden||Date.now()-start>120000)return;try{let r=await chrome.runtime.sendMessage({type:'totpVault:inline:list'});if(r?.ok&&!r.locked){theme(r.colorTheme);entries=r.entries||[];opened=Date.now();render(search?.value||'');countdown();return}}catch{}watch=setTimeout(check,650)};watch=setTimeout(check,350)}
function render(q=''){q=q.trim().toLowerCase();let a=entries.filter(e=>!q||`${e.name} ${e.issuer}`.toLowerCase().includes(q));list.replaceChildren();if(!a.length){list.innerHTML=`<div class=e>${entries.length?'Sin coincidencias.':'No hay TOTP guardados.'}</div>`;return}for(let e of a){let r=document.createElement('button');r.type='button';r.className='r';let i=document.createElement('span');i.className='i';if(e.icon?.type==='custom'&&e.icon.data){let im=document.createElement('img');im.src=e.icon.data;i.append(im)}else if(e.icon?.type==='builtin'&&ICONS.has(e.icon.key)){let im=document.createElement('img');im.src=chrome.runtime.getURL(`icons/services/${e.icon.key}.svg`);i.append(im)}else i.textContent=e.icon?.text||'T';let d=document.createElement('span');d.innerHTML=`<span class=n>${esc(e.name||'TOTP')}</span><span class=m>${esc(e.issuer||'TOTP')}</span>`;let c=document.createElement('span');c.className='c';c.innerHTML=`${e.codeVisible===false?(e.code||'••• •••'):fmt(e.code||'------')}<span class=s data-exp="${Date.now()+(+e.remaining||0)*1000}">${e.remaining||0}s</span>`;r.append(i,d,c);r.onclick=async ev=>{if(!ev.isTrusted)return;let x=await chrome.runtime.sendMessage({type:'totpVault:inline:code',entryId:e.id});if(x?.locked){locked();return}if(x?.ok){fill(x.code,x.autoSubmitMode||'off');close()}};list.append(r)}}
function native(e,v){let d=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value');d?.set?d.set.call(e,v):e.value=v;try{e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:v}))}catch{e.dispatchEvent(new Event('input',{bubbles:true}))}e.dispatchEvent(new Event('change',{bubbles:true}))}
function fill(code,mode){if(!target)return;let a=target.inputs;if(a.length>=code.length)a.slice(0,code.length).forEach((e,i)=>{e.focus();native(e,code[i])});else{a[0].focus();native(a[0],code)}if(mode!=='off')setTimeout(()=>submit(a[a.length-1],mode),220)}
function submit(anchor,mode){let form=anchor.form||anchor.closest('form'),vis=b=>{let r=b.getBoundingClientRect(),s=getComputedStyle(b);return !b.disabled&&r.width>0&&r.height>0&&s.display!='none'},neg=/(cancel|back|resend|recover|help|edit|cancelar|volver|reenviar|ayuda)/i,pos=/(verify|continue|submit|confirm|sign in|login|next|finish|check|verificar|continuar|siguiente|seguir|confirmar|enviar|acceder|aceptar|finalizar)/i,label=b=>`${b.innerText||''} ${b.value||''} ${b.getAttribute('aria-label')||''}`;if(form&&typeof form.requestSubmit==='function'){let b=[...form.querySelectorAll('button,input[type=submit]')].filter(x=>vis(x)&&String(x.type).toLowerCase()==='submit'&&!neg.test(label(x)));if(b.length===1){form.requestSubmit(b[0]);return}}if(mode==='maximum'){let b=[...document.querySelectorAll('button,input[type=submit],input[type=button],[role=button],a[role=button]')].filter(x=>vis(x)&&pos.test(label(x))&&!neg.test(label(x)));if(b.length===1)b[0].click()}}
function close(){if(panel)panel.hidden=true;root?.querySelector('.b')?.classList.remove('on');stop();clearTimeout(watch)}
function countdown(){stop();timer=setInterval(async()=>{if(panel?.hidden)return;let expired=false;for(let n of root.querySelectorAll('.s')){let x=Math.max(0,Math.ceil((+n.dataset.exp-Date.now())/1000));n.textContent=`${x}s`;if(!x)expired=true}if(expired&&Date.now()-opened>800){try{let r=await chrome.runtime.sendMessage({type:'totpVault:inline:list'});if(r?.ok&&!r.locked){entries=r.entries||[];opened=Date.now();render(search?.value||'')}}catch{}}},500)}
function stop(){if(timer)clearInterval(timer);timer=null}function fmt(x){x=String(x);return x.length===6?`${x.slice(0,3)} ${x.slice(3)}`:x.length===8?`${x.slice(0,4)} ${x.slice(4)}`:x}function esc(x){return String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function remove(clear=true){stop();clearTimeout(watch);host?.remove();host=root=panel=list=search=null;if(clear)target=null}
let scan=null;function rescan(){clearTimeout(scan);scan=setTimeout(()=>{if(target?.anchor?.isConnected&&visible(target.anchor)){position();return}setTarget(best())},120)}
document.addEventListener('focusin',e=>{if(e.target instanceof HTMLInputElement){let x=candidate(e.target);if(x)setTarget(x)}},true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel&&!panel.hidden)close()},true);addEventListener('scroll',position,true);addEventListener('resize',position,{passive:true});new MutationObserver(rescan).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style','hidden','disabled','readonly']});rescan();
})();
